export const INITIAL_LOAD = 'INITIAL_LOAD';
export const INITIAL_SORT = 'INITIAL_SORT';
export const SUCCESSFUL_STARTUP_SUBMIT = 'SUCCESSFUL_STARTUP_SUBMIT';
export const FAILED_STARTUP_SUBMIT = 'FAILED_STARTUP_SUBMIT';
export const LOG_OUT = 'LOG_OUT';
export const SUCCESSFUL_LOGIN = 'FAILED_LOGIN';
export const SUCCESSFUL_SIGNUP = 'SUCCESSFUL_SIGNUP';
