export const INITIAL_LOAD = 'INITIAL_LOAD';
export const SUCCESSFUL_STARTUP_SUBMIT = 'SUCCESSFUL_STARTUP_SUBMIT';
export const FAILED_STARTUP_SUBMIT = 'FAILED_STARTUP_SUBMIT';
export const SUCCESSFUL_LOGOUT = 'SUCCESSFUL_LOGOUT';
export const SUCCESSFUL_LOGIN = 'FAILED_LOGIN';
